import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { test } from "vitest";
import { ROOT, CLI, run, tempRoot, writeBriefFile, draftArgsFromGoal, draftAndApprove, recordArchitectureRequirement, readGoalPayloadFromPaths } from "./support/cli.js";

test("autogoal brief drafts a standard Nori Contract with assumptions and open questions", { tags: ["acceptance"] }, () => {
  const root = tempRoot();
  run(["install", "--root", root, "--json"]);
  const briefPath = path.join(root, "autogoal-brief.json");
  fs.writeFileSync(briefPath, JSON.stringify({
    goal_id: "autogoal-delivery-completion",
    goal: "让用户能判断一次 agent 交付是否真的完成，而不是只看到过程总结。",
    presentation: { language: "zh-CN" },
    acceptance_basis: {
      status: "draft",
      summary: "Draft generated by OpenNori autogoal from a rough idea. User approval is still required.",
      source: "autogoal",
      assumptions: [
        "用户希望最终批准的是标准 Nori Contract，而不是 autogoal 专用产物。",
        "目标完整闭环不能被降级成 MVP、第一版或任务列表。"
      ],
      open_questions: [
        "完成报告是否必须覆盖人工确认和工具观察两种证据来源？"
      ]
    },
    criteria: [
      {
        id: "AC-1",
        user_story: "作为用户，我能查看标准 Nori Contract Draft 并判断目标是否表达完整完成闭环。",
        measurement: "用户阅读 draft 的 Goal、验收标准、假设和开放问题。",
        threshold: "draft 是普通 Nori Contract，且没有 Autogoal Contract、MVP、第一版、阶段或任务列表字段。",
        risk: "high"
      }
    ]
  }, null, 2));

  const draft = run(["draft", "--root", root, "--brief", briefPath, "--json"]);
  assert.equal(draft.data.goal_id, "autogoal-delivery-completion");
  assert.equal(draft.data.state, "draft");
  assert.equal(draft.data.acceptance_basis.source, "autogoal");
  assert.equal(draft.data.criteria[0].id, "AC-1");
  const acceptance = fs.readFileSync(draft.data.acceptance_path, "utf8");
  assert.match(acceptance, /# autogoal-delivery-completion 验收契约/);
  assert.match(acceptance, /假设:/);
  assert.match(acceptance, /开放问题:/);
  assert.doesNotMatch(acceptance, /Implementation Plan|Task List/);
});

test("enhanced autogoal brief exposes reviewable discovery basis without new artifacts", { tags: ["acceptance"] }, () => {
  const root = tempRoot();
  run(["install", "--root", root, "--json"]);
  const briefPath = path.join(root, "enhanced-autogoal-brief.json");
  fs.writeFileSync(briefPath, JSON.stringify({
    goal_id: "enhanced-todolist",
    goal: "交付一个完整 todolist，让用户能管理待办并判断它是否可靠。",
    presentation: { language: "zh-CN" },
    acceptance_basis: {
      status: "draft",
      summary: "Draft generated by OpenNori enhanced autogoal from a rough idea.",
      source: "autogoal",
      mode: "enhanced",
      coverage_summary: [
        "任务创建、列表可见性、编辑、完成/取消完成、筛选、空态和错误状态。",
        "非法输入、删除/恢复、刷新持久化、UX 反馈和复查方式。"
      ],
      assumptions: [
        "待办数据至少要在刷新后保持。"
      ],
      open_questions: [
        "due date、tag、priority 是否属于本轮完成定义？"
      ],
      out_of_scope: [
        "多人协作和跨设备同步默认不在范围内，除非用户确认需要。"
      ]
    },
    criteria: [
      {
        id: "AC-1",
        user_story: "作为用户，我能创建一条待办并在列表中看到它。",
        measurement: "打开 todolist，输入标题并提交，再查看列表。",
        threshold: "新待办显示标题、未完成状态和可继续操作入口。",
        risk: "medium"
      }
    ]
  }, null, 2));

  const draft = run(["draft", "--root", root, "--brief", briefPath, "--json"]);
  assert.equal(draft.data.acceptance_basis.source, "autogoal");
  assert.equal(draft.data.acceptance_basis.mode, "enhanced");
  assert.equal(draft.data.acceptance_basis.coverage_summary.length, 2);

  const acceptance = fs.readFileSync(draft.data.acceptance_path, "utf8");
  assert.match(acceptance, /来源: autogoal/);
  assert.match(acceptance, /模式: enhanced/);
  assert.match(acceptance, /发现覆盖面:/);
  assert.match(acceptance, /范围外:/);
  assert.doesNotMatch(acceptance, /Autogoal Contract|Implementation Plan|Task List/);

  const status = run(["status", "--root", root, "--from-draft", "--goal", "enhanced-todolist", "--json"]);
  assert.equal(status.data.acceptance_basis.source, "autogoal");
  assert.equal(status.data.acceptance_basis.mode, "enhanced");
  assert.deepEqual(status.data.acceptance_basis.coverage_summary, [
    "任务创建、列表可见性、编辑、完成/取消完成、筛选、空态和错误状态。",
    "非法输入、删除/恢复、刷新持久化、UX 反馈和复查方式。"
  ]);

  const report = run(["report", "--root", root, "--from-draft", "--goal", "enhanced-todolist", "--json"]);
  const reportText = fs.readFileSync(report.data.report_path, "utf8");
  assert.match(reportText, /Source: autogoal/);
  assert.match(reportText, /Mode: enhanced/);
  assert.match(reportText, /Discovery coverage:/);
  assert.match(reportText, /Out of scope:/);
});

test("conversation adoption brief stays a draft Nori Contract awaiting user approval", { tags: ["acceptance"] }, () => {
  const root = tempRoot();
  run(["install", "--root", root, "--json"]);
  const briefPath = path.join(root, "conversation-brief.json");
  fs.writeFileSync(briefPath, JSON.stringify({
    goal_id: "settings-discussion-adoption",
    goal: "交付个人设置页面，让用户能修改资料并判断保存是否可靠。",
    presentation: { language: "zh-CN" },
    acceptance_basis: {
      status: "draft",
      summary: "Draft adopted from an in-progress AC discussion. User approval is still required.",
      source: "conversation",
      assumptions: [
        "用户和 agent 已经讨论过可编辑字段、保存反馈和失败恢复。",
        "当前目标是整理可批准的验收契约，不开始实现。"
      ],
      open_questions: [
        "头像上传失败时是否需要保留本地预览？"
      ]
    },
    criteria: [
      {
        id: "AC-1",
        user_story: "作为用户，我能打开个人设置页并编辑昵称、头像和简介。",
        measurement: "用户在设置页修改昵称、头像和简介后点击保存。",
        threshold: "保存成功后页面显示成功反馈，刷新后仍能看到更新后的值。",
        risk: "medium"
      },
      {
        id: "AC-2",
        user_story: "作为用户，我在保存失败时能理解发生了什么并继续处理自己的输入。",
        measurement: "用户触发保存失败或超时场景。",
        threshold: "页面显示可理解的失败提示，保留用户输入，并提供重试或返回路径。",
        risk: "high"
      }
    ]
  }, null, 2));

  const draft = run(["draft", "--root", root, "--brief", briefPath, "--json"]);
  assert.equal(draft.data.goal_id, "settings-discussion-adoption");
  assert.equal(draft.data.state, "draft");
  assert.equal(draft.data.acceptance_basis.status, "draft");
  assert.equal(draft.data.acceptance_basis.source, "conversation");
  assert.equal(draft.data.current_gap.id, "ACCEPTANCE-BASIS");
  assert.match(draft.data.acceptance_path, /\.opennori\/drafts\/settings-discussion-adoption\/README\.md$/);
  assert.equal(fs.existsSync(path.join(root, ".opennori", "current", "settings-discussion-adoption")), false);

  const acceptance = fs.readFileSync(draft.data.acceptance_path, "utf8");
  assert.match(acceptance, /# settings-discussion-adoption 验收契约/);
  assert.match(acceptance, /状态: draft/);
  assert.match(acceptance, /假设:/);
  assert.match(acceptance, /开放问题:/);
  assert.doesNotMatch(acceptance, /Implementation Plan|Task List|Autogoal Contract/);

  const list = run(["list", "--root", root, "--json"]);
  assert.equal(list.data.current_goals.length, 0);
  assert.equal(list.data.draft_goals.some((goal) => goal.goal_id === "settings-discussion-adoption"), true);
});

test("init creates markdown contract and evidence record", { tags: ["acceptance"] }, () => {
  const root = tempRoot();
  const payload = run(["draft", "--brief", "examples/opennori-self.json", "--root", root, "--json"]);

  assert.equal(payload.ok, true);
  assert.equal(payload.data.goal_id, "opennori-self");
  assert.equal(payload.data.current_gap.id, "AC-P-1");
  assert.equal(fs.existsSync(payload.data.acceptance_path), true);
  assert.equal(fs.existsSync(payload.data.evidence_path), true);

  const acceptance = fs.readFileSync(payload.data.acceptance_path, "utf8");
  assert.equal(payload.data.presentation.language, "zh-CN");
  assert.match(acceptance, /用户验收标准/);
  assert.match(acceptance, /语言: zh-CN/);
  assert.match(acceptance, /\| ID \| Layer \|/);
  assert.match(acceptance, /Codex 对话/);
  assert.doesNotMatch(acceptance, /Step 1/);
});

test("contract language is inferred for new briefs but not silently changed for legacy contracts", { tags: ["acceptance", "quick"] }, () => {
  const zhRoot = tempRoot();
  const zhDraft = run(["draft", "--brief", writeBriefFile(zhRoot, "交付设置页"), "--root", zhRoot, "--json"]);
  assert.equal(zhDraft.data.presentation.language, "zh-CN");
  assert.match(fs.readFileSync(zhDraft.data.acceptance_path, "utf8"), /## 表达偏好/);

  const legacyRoot = tempRoot();
  const legacyDraft = run(["draft", "--brief", writeBriefFile(legacyRoot, "交付设置页"), "--root", legacyRoot, "--json"]);
  const legacyContractPath = path.join(legacyRoot, ".opennori", "drafts", legacyDraft.data.goal_id, "contract.json");
  const legacyContract = JSON.parse(fs.readFileSync(legacyContractPath, "utf8"));
  delete legacyContract.presentation;
  fs.writeFileSync(legacyContractPath, JSON.stringify(legacyContract, null, 2));
  const legacyStatus = run(["status", "--root", legacyRoot, "--from-draft", "--goal", legacyDraft.data.goal_id, "--json"]);
  assert.equal(legacyStatus.data.presentation?.language, undefined);
});

test("goal dossier README is a review surface, while JSON files remain authoritative", { tags: ["acceptance", "quick"] }, () => {
  const root = tempRoot();
  const payload = run(["draft", "--brief", writeBriefFile(root, "Ship dossier boundary"), "--root", root, "--json"]);
  const readme = fs.readFileSync(payload.data.acceptance_path, "utf8");
  const goalDir = path.join(root, ".opennori", "drafts", payload.data.goal_id);

  assert.match(readme, /opennori\/goal-dossier-readme-v1 review-surface-only/);
  assert.match(readme, /This README is only for human and agent review/);
  assert.match(readme, /`contract\.json`, `ledger\.json`, and `criteria\/<AC-id>\/\*\.json` remain the OpenNori state source/);
  assert.equal(fs.existsSync(path.join(goalDir, "contract.json")), true);
  assert.equal(fs.existsSync(path.join(goalDir, "ledger.json")), true);
  assert.equal(fs.existsSync(path.join(goalDir, "criteria", "AC-1", "criterion.json")), true);
});

test("existing contract language changes only through explicit current approval", { tags: ["acceptance"] }, () => {
  const root = tempRoot();
  run([
    "draft",
    "--brief", writeBriefFile(root, "交付设置页", { goalId: "legacy-current-language", language: "zh-CN" }),
    "--language", "zh-CN",
    "--root", root,
    "--json"
  ]);
  run(["approve", "--root", root, "--summary", "User approved Chinese contract.", "--json"]);

  const goalDir = path.join(root, ".opennori", "current", "legacy-current-language");
  const acceptancePath = path.join(goalDir, "README.md");
  const contractPath = path.join(goalDir, "contract.json");
  const contract = JSON.parse(fs.readFileSync(contractPath, "utf8"));
  delete contract.presentation;
  fs.writeFileSync(contractPath, JSON.stringify(contract, null, 2));

  run([
    "evidence", "add",
    "--root", root,
    "--criterion", "AC-1",
    "--summary", "Evidence writes must not silently translate legacy contracts.",
    "--result", "passing",
    "--confidence", "verified",
    "--basis", "tool-observation",
    "--source-command", "opennori evidence add",
    "--json"
  ]);
  const afterEvidence = fs.readFileSync(acceptancePath, "utf8");
  assert.match(afterEvidence, /## Presentation/);
  assert.match(afterEvidence, /Language: en/);
  assert.doesNotMatch(afterEvidence, /语言: zh-CN/);

  const approvedLanguage = run([
    "approve",
    "--root", root,
    "--no-from-draft",
    "--language", "zh-CN",
    "--summary", "User explicitly approved Chinese presentation.",
    "--json"
  ]);
  assert.equal(approvedLanguage.data.presentation.language, "zh-CN");
  assert.match(fs.readFileSync(acceptancePath, "utf8"), /语言: zh-CN/);
  assert.equal(fs.existsSync(acceptancePath), true);
});

test("next returns the current acceptance gap, not a process step", { tags: ["acceptance"] }, () => {
  const root = tempRoot();
  const init = run(["draft", "--brief", "examples/opennori-self.json", "--root", root, "--json"]);
  const payload = run([
    "next",
    "--acceptance", init.data.acceptance_path,
    "--evidence", init.data.evidence_path,
    "--json"
  ]);

  assert.equal(payload.ok, true);
  assert.equal(payload.data.current_gap.id, "AC-P-1");
  assert.match(payload.data.current_gap.reason, /no user-understandable evidence/);
});

test("resume and status recover the current goal from repository files", { tags: ["acceptance"] }, () => {
  const root = tempRoot();
  const init = draftAndApprove(["--brief", "examples/opennori-self.json", "--root", root, "--json"]);

  const resume = run(["resume", "--root", root, "--json"]);
  assert.equal(resume.ok, true);
  assert.equal(resume.data.goal_id, "opennori-self");
  assert.equal(resume.data.current_gap.id, "AC-P-1");
  assert.equal(resume.data.completion.complete, false);
  assert.equal(resume.data.next_recommendation.status, "architecture-requirement-required");
  assert.equal(resume.data.agent_next.state, "architecture_requirement_needs_decision");
  assert.equal(resume.data.agent_next.recommended_skill, "nori-architecture-brainstorm");
  assert.equal(resume.data.next_recommendation.focus, "AC-P-1");
  assert.equal(resume.next_actions.some((action) => /required, not_required, or waived/.test(action)), true);

  const requirement = recordArchitectureRequirement(
    root,
    "opennori-self",
    "required",
    "The self goal changes OpenNori protocol, state, and routing behavior."
  );
  assert.equal(requirement.data.agent_next.state, "architecture_needs_review");

  run([
    "architecture", "baseline",
    "--root", root,
    "--goal", "OpenNori accepts goals as contracts and reports completion through reviewable evidence.",
    "--goal-id", "opennori-self",
    "--confirm",
    "--json"
  ]);

  const afterBaseline = run(["resume", "--root", root, "--json"]);
  assert.equal(afterBaseline.data.next_recommendation.status, "work-on-current-gap");
  assert.equal(afterBaseline.data.agent_next.state, "work_on_current_gap");
  assert.equal(afterBaseline.data.agent_next.recommended_skill, "nori-architecture-apply");
  assert.match(afterBaseline.data.agent_next.instruction, /Architecture Baseline/);
  assert.equal(afterBaseline.next_actions.some((action) => /AC-P-1/.test(action)), true);

  run([
    "evidence", "add",
    "--root", root,
    "--criterion", "AC-P-1",
    "--kind", "test-summary",
    "--summary", "Draft acceptance criteria are visible.",
    "--result", "passing",
    "--json"
  ]);

  const status = run(["status", "--root", root, "--json"]);
  assert.equal(status.data.current_gap.id, "AC-P-2");
  assert.equal(status.data.intervention.required, false);

  const acceptance = fs.readFileSync(init.data.acceptance_path, "utf8");
  assert.match(acceptance, /AC-P-1 .* passing/);
});

test("draft requires user approval before completion evidence can finish the workflow", { tags: ["acceptance"] }, () => {
  const root = tempRoot();
  const draft = run(["draft", ...draftArgsFromGoal(root, "Ship an OpenNori-backed task")]);
  assert.equal(draft.data.acceptance_basis.status, "draft");
  assert.equal(draft.data.current_gap.id, "ACCEPTANCE-BASIS");

  const acceptance = fs.readFileSync(draft.data.acceptance_path, "utf8");
  assert.match(acceptance, /## Acceptance Basis/);
  assert.match(acceptance, /Status: draft/);

  const ledger = JSON.parse(fs.readFileSync(draft.data.evidence_path, "utf8"));
  assert.equal(ledger.status, "draft");
  for (const criterion of Object.keys(ledger.criteria)) {
    run([
      "evidence", "add",
      "--acceptance", draft.data.acceptance_path,
      "--evidence", draft.data.evidence_path,
      "--criterion", criterion,
      "--kind", "test-summary",
      "--summary", `${criterion} has evidence.`,
      "--result", "passing",
      "--source-command", "opennori status --root . --json",
      "--source-path", ".opennori/reports/draft.report.md",
      "--reviewability", "Run status and inspect the report artifact.",
      "--limitations", "This is a test fixture for approval gating.",
      "--json"
    ]);
  }

  const beforeApprove = run([
    "evaluate",
    "--acceptance", draft.data.acceptance_path,
    "--evidence", draft.data.evidence_path,
    "--json"
  ]);
  assert.equal(beforeApprove.data.workflow_status, "draft");
  assert.equal(beforeApprove.data.current_gap.id, "ACCEPTANCE-BASIS");

  const approved = run(["approve", "--root", root, "--summary", "User approved criteria.", "--json"]);
  assert.equal(approved.data.acceptance_basis.status, "approved");
  assert.equal(approved.data.workflow_status, "complete");
});

test("brainstorm creates selectable acceptance directions, not a process plan", { tags: ["acceptance"] }, () => {
  const root = tempRoot();
  const candidates = JSON.stringify({
    candidates: [
      {
        id: "A",
        title: "头脑风暴验收入口",
        user_value: "用户能从粗略想法看到可选择的验收方向。",
        suggested_goal_template: "让 OpenNori 支持头脑风暴入口。",
        acceptance_directions: ["作为用户，我能看到候选方向并选择或改写。"],
        risks: ["候选方向仍需转成 NoriBrief 后才能 draft。"]
      }
    ]
  });
  const brainstorm = run([
    "brainstorm",
    "--idea", "我想让 OpenNori 支持头脑风暴",
    "--candidates", candidates,
    "--root", root,
    "--json"
  ]);

  assert.equal(brainstorm.data.status, "draft-source");
  assert.equal(brainstorm.data.is_acceptance_contract, false);
  assert.equal(brainstorm.data.candidates.length, 1);
  assert.equal(brainstorm.data.presentation.language, "zh-CN");
  assert.equal(fs.existsSync(brainstorm.data.brainstorm_path), true);
  assert.equal(fs.existsSync(brainstorm.data.markdown_path), true);

  const text = fs.readFileSync(brainstorm.data.markdown_path, "utf8");
  assert.match(text, /验收方向/);
  assert.match(text, /不是计划、Nori Contract 或完成证据/);
  assert.doesNotMatch(text, /Implementation plan/);
  assert.doesNotMatch(text, /Step 1/);

  const draft = run(["draft", ...draftArgsFromGoal(root, "让 OpenNori 支持头脑风暴入口", {
    language: "zh-CN",
    goalId: "brainstorm-contract"
  })]);
  assert.equal(draft.data.acceptance_basis.status, "draft");
  assert.equal(draft.data.current_gap.id, "ACCEPTANCE-BASIS");
  assert.equal(draft.data.criteria.every((criterion) => criterion.user_story.startsWith("作为用户")), true);
});

test("discover writes a non-contract question source before draft", { tags: ["acceptance"] }, () => {
  const root = tempRoot();
  const questions = JSON.stringify({
    gaps: [
      {
        id: "field-scope",
        question: "哪些字段可以修改，哪些字段只读？",
        why: "用户需要知道设置页的可编辑范围。"
      },
      {
        id: "failure-case",
        question: "保存失败时用户应该看到什么？",
        why: "失败反馈会影响用户判断功能是否完成。"
      }
    ]
  });
  const discovery = run([
    "discover",
    "--goal", "做一个设置页，用户可以修改个人资料，保存后刷新仍然生效，失败时有提示。",
    "--questions", questions,
    "--root", root,
    "--json"
  ]);

  assert.equal(discovery.data.status, "needs-user-answers");
  assert.equal(discovery.data.presentation.language, "zh-CN");
  assert.equal(discovery.data.is_acceptance_contract, false);
  assert.equal(fs.existsSync(discovery.data.discovery_path), true);
  assert.equal(fs.existsSync(discovery.data.markdown_path), true);
  assert.equal(fs.existsSync(path.join(root, ".opennori", "active")), false);

  assert.equal(discovery.data.gaps.length > 0, true);
  assert.equal(discovery.data.gaps.every((gap) => typeof gap.question === "string" && gap.question.length > 0), true);
  assert.equal(discovery.data.gaps.every((gap) => ["must-answer", "can-default"].includes(gap.priority)), true);

  const text = fs.readFileSync(discovery.data.markdown_path, "utf8");
  assert.match(text, /验收发现/);
  assert.match(text, /不是 Nori Contract、过程计划或完成证据/);
  assert.doesNotMatch(text, /Implementation plan/);
});

test("draft preserves explicit contract language preference for human-readable goal and AC", { tags: ["acceptance"] }, () => {
  const root = tempRoot();
  const zhDraft = run([
    "draft",
    "--brief", writeBriefFile(root, "Ship a settings page", { language: "zh-CN" }),
    "--language", "zh-CN",
    "--root", root,
    "--json"
  ]);
  assert.equal(zhDraft.data.presentation.language, "zh-CN");
  assert.equal(zhDraft.data.criteria.every((criterion) => criterion.user_story.startsWith("作为用户")), true);
  const zhMarkdown = fs.readFileSync(zhDraft.data.acceptance_path, "utf8");
  assert.match(zhMarkdown, /## 表达偏好/);
  assert.match(zhMarkdown, /语言: zh-CN/);

  const enDraft = run([
    "draft",
    "--brief", writeBriefFile(root, "交付设置页", { language: "en", goalId: "settings-page-en" }),
    "--language", "en",
    "--root", root,
    "--json"
  ]);
  assert.equal(enDraft.data.presentation.language, "en");
  assert.equal(enDraft.data.criteria.every((criterion) => criterion.user_story.startsWith("As a user")), true);
  const enMarkdown = fs.readFileSync(enDraft.data.acceptance_path, "utf8");
  assert.match(enMarkdown, /## Presentation/);
  assert.match(enMarkdown, /Language: en/);
});

test("draft preserves Skill-provided user-readable acceptance fields", { tags: ["acceptance"] }, () => {
  const root = tempRoot();
  const criteria = [
    {
      id: "AC-1",
      layer: "operator",
      user_story: "作为用户，我能从顶部导航打开 Account Settings 并进入 Profile 标签页。",
      measurement: "打开 Account Settings，再进入 Profile 标签页查看资料表单。",
      threshold: "Profile 标签页显示昵称、头像和简介字段，邮箱、手机号和密码显示为只读或不在本轮编辑范围。"
    },
    {
      id: "AC-2",
      layer: "operator",
      user_story: "作为用户，我能按规则编辑昵称、头像和简介。",
      measurement: "输入 2-30 个字符的昵称、最多 160 个字符的简介，并选择不超过 2MB 的 PNG/JPEG 头像。",
      threshold: "合法输入可以提交；不合法昵称、过长简介或错误头像格式会显示可理解的校验提示。"
    },
    {
      id: "AC-3",
      layer: "operator",
      user_story: "作为用户，我保存成功后能立即确认资料已更新。",
      measurement: "修改昵称、头像和简介后点击保存。",
      threshold: "页面显示成功提示，并在 Profile 标签页立即看到更新后的昵称、头像和简介。"
    },
    {
      id: "AC-4",
      layer: "operator",
      user_story: "作为用户，我刷新或重新打开页面后仍能看到保存后的资料。",
      measurement: "保存后刷新页面，或关闭后重新打开 Account Settings 的 Profile 标签页。",
      threshold: "昵称、头像和简介仍然保持保存后的值。"
    },
    {
      id: "AC-5",
      layer: "operator",
      user_story: "作为用户，我在网络失败时能看到失败提示且输入不丢失。",
      measurement: "模拟保存请求失败后点击保存。",
      threshold: "页面显示网络错误提示，保留表单中的用户输入，不覆盖旧资料。"
    },
    {
      id: "AC-6",
      layer: "protocol",
      user_story: "作为评审者，我能用浏览器证据复查设置页是否完成。",
      measurement: "执行成功保存、刷新持久化和网络失败场景，并保存截图或报告。",
      threshold: "证据能说明入口、字段范围、规则、成功反馈、持久化、失败恢复和未覆盖范围。"
    }
  ];
  const briefPath = writeBriefFile(root, "Ship a settings page where users edit profile details", {
    language: "zh-CN",
    goalId: "settings-profile",
    criteria
  });

  const draft = run([
    "draft",
    "--brief", briefPath,
    "--root", root,
    "--language", "zh-CN",
    "--json"
  ]);

  assert.equal(draft.data.acceptance_basis.status, "draft");
  assert.equal(draft.data.presentation.language, "zh-CN");
  assert.match(draft.data.acceptance_basis.summary, /Skill-prepared acceptance brief/);
  assert.deepEqual(
    draft.data.criteria.map((criterion) => ({
      id: criterion.id,
      layer: criterion.layer,
      user_story: criterion.user_story,
      measurement: criterion.measurement,
      threshold: criterion.threshold
    })),
    criteria
  );
  assert.equal(draft.data.criteria.every((criterion) => criterion.required === true), true);
  assert.equal(draft.data.criteria.every((criterion) => criterion.risk === "medium"), true);
});

test("criterion update preserves the revised acceptance basis and clears stale evidence", { tags: ["acceptance"] }, () => {
  const root = tempRoot();
  const init = draftAndApprove(["--brief", "examples/opennori-self.json", "--root", root, "--json"]);

  run([
    "evidence", "add",
    "--root", root,
    "--criterion", "AC-P-1",
    "--kind", "test-summary",
    "--summary", "Old criterion had evidence.",
    "--result", "passing",
    "--json"
  ]);

  const updated = run([
    "criterion", "update",
    "--root", root,
    "--criterion", "AC-P-1",
    "--user-story", "作为用户，我打开 current Nori Contract 后，能在 30 秒内判断当前缺口。",
    "--measurement", "打开 current Nori Contract 并阅读当前状态。",
    "--threshold", "30 秒内能判断当前缺口。",
    "--summary", "User tightened AC-P-1 threshold.",
    "--json"
  ]);

  assert.equal(updated.data.acceptance_basis.status, "approved");
  assert.equal(updated.data.current_gap.id, "AC-P-1");
  assert.equal(updated.data.current_gap.user_story, "作为用户，我打开 current Nori Contract 后，能在 30 秒内判断当前缺口。");

  const payload = readGoalPayloadFromPaths(init.data.acceptance_path, init.data.evidence_path);
  assert.equal(payload.ledger.criteria["AC-P-1"].status, "unknown");
  assert.equal(payload.ledger.criteria["AC-P-1"].evidence.length, 0);
});

test("criterion update on a draft keeps the contract awaiting AC review", { tags: ["acceptance"] }, () => {
  const root = tempRoot();
  const briefPath = writeBriefFile(root, "交付 AW 项目登记和选择能力", {
    goalId: "aw-project-registry",
    language: "zh-CN",
    criteria: [
      {
        id: "AC-1",
        layer: "operator",
        user_story: "作为用户，我能在 AW 项目列表选择一个项目。",
        measurement: "打开 AW 项目列表并选择项目。",
        threshold: "被选项目显示为当前项目。"
      }
    ]
  });
  const draft = run(["draft", "--brief", briefPath, "--root", root, "--json"]);

  run([
    "profile", "add",
    "--root", root,
    "--from-draft",
    "--goal", "aw-project-registry",
    "--id", "ui-component-library-first",
    "--type", "constraint",
    "--name", "优先使用项目现有组件库",
    "--strength", "must",
    "--purpose", "UI 实现应先复用现有组件库。",
    "--scope", "AW UI work",
    "--json"
  ]);

  const updated = run([
    "criterion", "update",
    "--root", root,
    "--from-draft",
    "--goal", "aw-project-registry",
    "--criterion", "AC-1",
    "--user-story", "作为用户，我能在 AW 项目登记层新增、查看、修改、解绑并选择项目。",
    "--measurement", "打开 AW 项目登记入口，新增或修改项目登记信息，查看可见项目列表，解绑一个登记项，并选择一个项目。",
    "--threshold", "增删改查只影响 AW 登记信息和可见项目列表；解绑不会删除本地项目目录；选中的项目状态清楚可见。",
    "--summary", "用户在 AC Review Loop 中修订 AC-1。",
    "--json"
  ]);

  assert.equal(updated.data.acceptance_basis.status, "draft");
  assert.equal(updated.data.current_gap.id, "ACCEPTANCE-BASIS");
  assert.equal(updated.data.workflow_status, "draft");
  const status = run(["status", "--root", root, "--from-draft", "--goal", "aw-project-registry", "--json"]);
  assert.equal(status.data.acceptance_basis.status, "draft");
  assert.equal(status.data.current_gap.id, "ACCEPTANCE-BASIS");
  assert.equal(status.data.workflow_status, "draft");
  const payload = readGoalPayloadFromPaths(draft.data.acceptance_path, draft.data.evidence_path);
  assert.equal(payload.contract.acceptance_basis.status, "draft");
  assert.equal(payload.contract.acceptance_basis.approved_at, undefined);
  assert.equal(payload.ledger.status, "draft");
});

test("criterion add on a draft keeps the contract awaiting AC review", { tags: ["acceptance"] }, () => {
  const root = tempRoot();
  const briefPath = writeBriefFile(root, "交付 AW 项目设置能力", {
    goalId: "aw-project-settings",
    language: "zh-CN",
    criteria: [
      {
        id: "AC-1",
        layer: "operator",
        user_story: "作为用户，我能在 AW 项目详情页查看项目名称。",
        measurement: "打开 AW 项目详情页并查看项目名称展示。",
        threshold: "当前项目名称可见，并与项目登记状态一致。"
      }
    ]
  });
  const draft = run(["draft", "--brief", briefPath, "--root", root, "--json"]);

  const added = run([
    "criterion", "add",
    "--root", root,
    "--from-draft",
    "--goal", "aw-project-settings",
    "--id", "AC-14",
    "--user-story", "作为用户，我能从 AW 项目详情页打开设置入口并修改项目分类。",
    "--measurement", "打开项目详情页，点击设置入口，在设置表单中修改项目分类并保存。",
    "--threshold", "保存成功后详情页显示新的分类；刷新后分类仍然存在；保存失败时显示可理解的错误和重试入口。",
    "--summary", "AC Review Loop discovered the missing settings acceptance boundary.",
    "--json"
  ]);

  assert.equal(added.data.criterion.id, "AC-14");
  assert.equal(added.data.acceptance_basis.status, "draft");
  assert.equal(added.data.current_gap.id, "ACCEPTANCE-BASIS");
  assert.equal(added.data.workflow_status, "draft");

  const status = run(["status", "--root", root, "--from-draft", "--goal", "aw-project-settings", "--json"]);
  assert.equal(status.data.acceptance_basis.status, "draft");
  assert.equal(status.data.current_gap.id, "ACCEPTANCE-BASIS");
  assert.equal(status.data.workflow_status, "draft");

  const payload = readGoalPayloadFromPaths(draft.data.acceptance_path, draft.data.evidence_path);
  assert.equal(payload.contract.criteria.some((criterion) => criterion.id === "AC-14"), true);
  assert.equal(payload.contract.acceptance_basis.status, "draft");
  assert.equal(payload.contract.acceptance_basis.approved_at, undefined);
  assert.equal(payload.ledger.status, "draft");
  assert.equal(payload.ledger.criteria["AC-14"].status, "unknown");
  assert.match(fs.readFileSync(draft.data.acceptance_path, "utf8"), /AC-14/);

  const manifest = JSON.parse(fs.readFileSync(path.join(root, ".opennori", "manifest.json"), "utf8"));
  assert.equal(manifest.draft_goals.some((goal) => goal.goal_id === "aw-project-settings"), true);
});

test("criterion add preserves contract and ledger consistency", { tags: ["acceptance"] }, () => {
  const root = tempRoot();
  const init = draftAndApprove(["--brief", "examples/opennori-self.json", "--root", root, "--json"]);

  const added = run([
    "criterion", "add",
    "--root", root,
    "--id", "AC-Z-99",
    "--user-story", "作为用户，我能确认 OpenNori 是一个不可拆开的 agent capability bundle。",
    "--measurement", "阅读 README、Plugin 说明、Skill 边界和官网 Start 区域。",
    "--threshold", "主路径表达为安装和使用 OpenNori capability bundle，CLI 只作为 Skills 使用的 deterministic state layer 和高级/CI 入口。",
    "--summary", "User added the capability bundle boundary AC.",
    "--json"
  ]);

  assert.equal(added.data.criterion.id, "AC-Z-99");
  assert.equal(added.data.workflow_status, "active");

  const payload = readGoalPayloadFromPaths(init.data.acceptance_path, init.data.evidence_path);
  assert.equal(payload.contract.criteria.some((criterion) => criterion.id === "AC-Z-99"), true);
  assert.equal(payload.ledger.criteria["AC-Z-99"].status, "unknown");

  const duplicate = spawnSync(process.execPath, [
    CLI,
    "criterion",
    "add",
    "--root", root,
    "--id", "AC-Z-99",
    "--user-story", "作为用户，我不会看到重复 AC。",
    "--measurement", "再次添加同一 id。",
    "--threshold", "命令失败。",
    "--json"
  ], {
    cwd: ROOT,
    encoding: "utf8"
  });
  assert.equal(duplicate.status, 1);
  const duplicatePayload = JSON.parse(duplicate.stdout || duplicate.stderr);
  assert.equal(duplicatePayload.ok, false);
  assert.equal(duplicatePayload.error.type, "unexpected_error");
  assert.match(duplicatePayload.error.message, /Criterion already exists/);
});

test("drafted generic goals stay blocked on acceptance approval", { tags: ["acceptance"] }, () => {
  const root = tempRoot();
  const draft = run(["draft", ...draftArgsFromGoal(root, "Ship a settings page where users edit profile details")]);
  assert.equal(draft.ok, true);
  assert.match(draft.data.acceptance_basis.summary, /Skill-prepared acceptance brief/);
  assert.equal(draft.data.acceptance_basis.status, "draft");
  assert.equal(draft.data.current_gap.id, "ACCEPTANCE-BASIS");
});

test("check does not rewrite existing contracts while reporting objective state", { tags: ["acceptance"] }, () => {
  const root = tempRoot();
  const brief = path.join(root, "existing-contract.json");
  fs.writeFileSync(brief, JSON.stringify({
    goal_id: "existing-contract",
    goal: "Settings page",
    acceptance_basis: { status: "approved", summary: "Existing project contract." },
    criteria: [
      {
        id: "AC-1",
        user_story: "作为用户，我打开设置页后，能修改个人资料并保存，失败时看到提示。",
        measurement: "打开设置页，修改个人资料，点击保存。",
        threshold: "刷新后仍然生效；失败时有提示。"
      }
    ]
  }));

  const init = run(["draft", "--brief", brief, "--root", root, "--json"]);
  const before = fs.readFileSync(init.data.evidence_path, "utf8");
  const check = run(["check", "--acceptance", init.data.acceptance_path, "--evidence", init.data.evidence_path, "--json"]);
  const after = fs.readFileSync(init.data.evidence_path, "utf8");

  assert.equal(check.ok, true);
  assert.equal(check.data.acceptance_review.status, "clear");
  assert.equal(check.warnings.some((warning) => warning.type === "acceptance_review"), false);
  assert.equal(check.data.architecture_check.status, "needs-action");
  assert.equal(after, before);
});
